hospitalAS.Web/Controllers/AppointmentController.cs
using hospitalAS.Business.Interfaces;
using hospitalAS.Dto.AppointmentDtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace hospitalAS.Web.Controllers
{
    [Authorize]
    public class AppointmentController : Controller
    {
        private readonly IAppointmentService _appointmentService;
        private readonly IUserService _userService;
        private readonly IHospitalService _hospitalService;
        private readonly IPoliclinicService _policlinicService;
        public AppointmentController(IAppointmentService appointmentService, IPoliclinicService policlinicService, IHospitalService hospitalService, IUserService userService)
        {
            _userService = userService;
            _hospitalService = hospitalService;
            _appointmentService = appointmentService;
            _policlinicService = policlinicService;
        }
        private async Task<int> GetUserId()
        {
            var identityNumber = User.Claims.FirstOrDefault(o => o.Type == ClaimTypes.NameIdentifier).Value;
            int userId = await _userService.GetUserIdByIdentityNumber(identityNumber);
            return userId;
        }
        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> Index()
        {
            ViewBag.Hospitals = new SelectList(await _hospitalService.GetAllHospitals(), "Id", "Name");
            var appointments = await _appointmentService.GetAllAppointmentsByUserId(await GetUserId());
            return View(appointments);
        }
        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> PoliclinicList(int id)
        {
            var jsonString = JsonConvert.SerializeObject(await _policlinicService.GetPoliclinicsByHospitalId(id));
            return Json(jsonString);
        }
        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> DoctorList(int id)
        {
            var jsonString = JsonConvert.SerializeObject(await _userService.GetDoctorsByPoliclinicId(id));
            return Json(jsonString);
        }
        [Authorize(Roles = "Patient")]
        [HttpPost]
        public async Task<IActionResult> TakeAnAppointment(AddAppointmentDto model)
        {
             model.PatientId = await GetUserId(); 
            await _appointmentService.AddAppointment(model);
            return Json("true");
        }
        [Authorize(Roles = "Doctor")]
        public async Task<IActionResult> PatientList()
        {
            var patients = await _appointmentService.GetAllAppointmentsByDoctorId(await GetUserId());
            return View(patients);
        }
        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> OutOfDateAppointment()
        {
            var appointments = await _appointmentService.GetOutOfDateAppointmentByUserId(await GetUserId());
            return View(appointments);
        }
        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> CancelAppointment(int id)
        {
            await _appointmentService.DeleteAppointment(id);
            return RedirectToAction("Index");
        }
    }
}

hospitalAS.Web/Controllers/PrescriptionController.cs
using hospitalAS.Business.Interfaces;
using hospitalAS.Dto.PrescriptionDtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace hospitalAS.Web.Controllers
{
    [Authorize]
    public class PrescriptionController : Controller
    {
        private readonly IPrescriptionService _prescriptionService;
        public PrescriptionController( IPrescriptionService prescriptionService)
        {
            _prescriptionService = prescriptionService;
        }

        public async Task<IActionResult> Index(int id)
        {
            ViewBag.AppointmentId = id;
            var prescriptions = await _prescriptionService.GetAllPrescriptionByAppointmentId(id);
            return View(prescriptions);
        }
        [Authorize(Roles = "Admin,Doctor")]
        public IActionResult AddPrescription(int id)
        {
            AddPrescriptionDto model = new AddPrescriptionDto();
            model.AppointmentId = id;
            return View(model);
        }
        [Authorize(Roles = "Admin,Doctor")]
        [HttpPost]
        public async Task<IActionResult> AddPrescription(AddPrescriptionDto model)
        {
            if (ModelState.IsValid)
            {
                await _prescriptionService.AddPresscription(model);
                return RedirectToAction("Index", new { id = model.AppointmentId });
            }
            return View(model);

        }
        [Authorize(Roles = "Admin,Doctor")]
        public async Task<IActionResult> DeletePrescription(int id,int appointmentId)
        {
            await _prescriptionService.DeletePrescription(id);
            return RedirectToAction("Index", new { id = appointmentId });
        }

    }
}

hospitalAS.Web/Views/Appointment/Index.cshtml
@model IEnumerable<ListAppointmentDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card mt-5">
    <div class="card-header">
        Randevularım
        @if (User.IsInRole("Patient") && User.Identity.IsAuthenticated)
        {
            <button type="button" class="btn btn-outline-info btn-lg px-3 float-end" data-bs-toggle="modal" data-bs-target="#appointmentModal">
                Randevu Al
            </button>
        }
    </div>

    <div class="mt-4 row card-body ">

        <div class="col-md-12">
            @if (Model != null)
            {
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Tarih</th>
                            <th scope="col">Doktor</th>
                            <th scope="col">Poliklinik</th>
                            <th scope="col">Hastane</th>
                            <th scope="col">Aktif randevu mu?</th>
                            <th scope="col">İşlemler</th>

                        </tr>
                    </thead>
                    <tbody>


                        @foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">@item.Date.ToLocalTime()</th>
                                <td>@item.UserName</td>
                                <td>@item.PoliclinicName</td>
                                <td>@item.HospitalName</td>                               
                                @if (item.IsActive == true)
                                {
                                    <td><span class="badge bg-success">Aktif Randevu</span></td>
                                    <td>
                                        @if (User.IsInRole("Patient") && User.Identity.IsAuthenticated)
                                        {<a asp-action="CancelAppointment" asp-controller="Appointment" asp-route-id="@item.Id" class="btn btn-danger">İptal Et</a>
                                        }
                                    </td>
                                }
                                else
                                {
                                    <td><span class="badge bg-danger">İptal Edildi</span></td>
                                    <td></td>
                                }

                            </tr>
                        }

                    </tbody>
                </table>
            }
            else
            {
                <p>Randevunuz bulunmamaktadır</p>
            }
        </div>
    </div>

</div>


<!-- Modal -->
<div class="modal fade " id="appointmentModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Randevu Al</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post">
                    <div class="mt-10">
                        <label class="float-left">Hastane Seçiniz</label>
                        <select class="form-select wide" onchange="hospitalChange()" id="hospitalId" asp-items="@ViewBag.Hospitals">
                        </select>
                    </div>
                    <div class="mt-10">
                        <label class="float-left">Poliklinik Seçiniz</label>
                        <select disabled class="form-select wide" onchange="policlinicChange()" id="policlinicId">
                        </select>
                    </div>
                    <div class="mt-10">
                        <label class="float-left">DoKtor Seçiniz</label>
                        <select disabled class="form-select wide" id="doctorId">
                        </select>
                    </div>
                    <div class="mt-10">
                        <label class="float-left">Randevu Tarihi Seçiniz</label>
                        <input type="datetime-local" id="date" />
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                <button type="button" onclick="takeAnAppoinment()" class="btn btn-primary">Randevu Al</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        //hastane seçimine göre poliklinik getirme
        function hospitalChange() {

            var id = document.getElementById("hospitalId").value;
            if (id > 0) {
                $.ajax({
                    method: "GET",
                    url: "/Appointment/PoliclinicList/" + id,
                }).done(function (content) {
                    $("#policlinicId").attr("disabled", false);
                    $("#policlinicId").removeClass("text-muted");
                    $("#policlinicId").empty();
                    $("#policlinicId").append('<option value="-1">Poliklinik Seçiniz</option>');

                    let policlinic = JSON.parse(content);
                    for (var i = 0; i < policlinic.length; i++) {
                        var opt = '<option value="' + policlinic[i].Id + '">' + policlinic[i].Name + '</option>';
                        $("#policlinicId").append(opt);
                    }
                }).fail(function (error) {

                });
            } else {
                $("#doctorId").empty();
                $("#doctorId").append('<option value="-1">Doktor Seçiniz</option>');
                $("#doctorId").attr("disabled", true);
                $("#doctorId").addClass("text-muted");
            }
        }
        //poliklinik seçimine göre doktor getirme
        function policlinicChange() {
            var id = document.getElementById("policlinicId").value;
            if (id > 0) {
                $.ajax({
                    method: "GET",
                    url: "/Appointment/DoctorList/" + id,
                }).done(function (content) {
                    $("#doctorId").attr("disabled", false);
                    $("#doctorId").removeClass("text-muted");
                    $("#doctorId").empty();
                    $("#doctorId").append('<option value="-1">Doktor Seçiniz</option>');

                    let doctor = JSON.parse(content);
                    for (var i = 0; i < doctor.length; i++) {
                        var opt = '<option value="' + doctor[i].Id + '">' + doctor[i].Name + ' ' + doctor[i].Surname + '</option>';
                        $("#doctorId").append(opt);
                    }
                }).fail(function (error) {

                });
            } else {
                $("#doctorId").empty();
                $("#doctorId").append('<option value="-1">Doktor Seçiniz</option>');
                $("#doctorId").attr("disabled", true);
                $("#doctorId").addClass("text-muted");
            }
        }
        //randevu alma
        function takeAnAppoinment() {
            var formData = {
                hospitalId: $("#hospitalId").val(),
                policlinicId: $("#policlinicId").val(),
                doctorId: $("#doctorId").val(),
                date: $("#date").val(),
            };
            $.ajax({
                method: 'POST',
                url: '/Appointment/TakeAnAppointment/',
                data: formData
            }).done(function (data) {
                if (data == "true") {
                    alertify.success("Kaydınız başarıyla oluşturuldu");
                }
                else {
                    alertify.success("Kaydınız başarısız lütfen tekrar deneyin");
                }
            })
        }

    </script>

}

hospitalAS.Web/Views/Appointment/OutOfDateAppointment.cshtml
@model IEnumerable<ListAppointmentDto>
@{
    ViewData["Title"] = "OutOfDateAppointment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card mt-5">
    <div class="card-header">
        Randevu Geçmişi   
    </div>

    <div class="mt-4 row card-body ">

        <div class="col-md-12">
            @if (Model != null)
            {
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Tarih</th>
                            <th scope="col">Doktor</th>
                            <th scope="col">Poliklinik</th>
                            <th scope="col">Hastane</th>
                            <th scope="col">Reçete</th>
                            <th scope="col">Aktif randevu mu?</th>

                        </tr>
                    </thead>
                    <tbody>


                        @foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">@item.Date.ToLocalTime()</th>
                                <td>@item.UserName</td>
                                <td>@item.PoliclinicName</td>
                                <td>@item.HospitalName</td>
                                <td><a asp-action="Index" asp-controller="Prescription" asp-route-id="@item.Id" class="btn btn-info">Reçete</a></td>
                                @if (item.IsActive == true)
                                {
                                    <td><span class="badge bg-success">Aktif Randevu</span></td>
                                }
                                else
                                {
                                    <td><span class="badge bg-danger">İptal Edildi</span></td>
                                }

                            </tr>
                        }

                    </tbody>
                </table>
            }
            else
            {
                <p>Geçmiş randevunuz bulunmamaktadır</p>
            }
        </div>
    </div>

</div>

hospitalAS.Web/Views/Appointment/PatientList.cshtml
@model IEnumerable<ListAppointmentDto>
@{
    ViewData["Title"] = "PatientList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card mt-5">
    <div class="card-header">
        Hasta Randevuları
    </div>

    <div class="mt-4 row card-body ">

        <div class="col-md-12">
            @if (Model != null)
            {
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Tarih</th>
                            <th scope="col">Hasta</th>
                            <th scope="col">Poliklinik</th>
                            <th scope="col">Hastane</th>
                            <th scope="col">Aktif randevu mu?</th>
                            <th scope="col">İşlemler</th>

                        </tr>
                    </thead>
                    <tbody>


                        @foreach (var item in Model)
                        {
                        <tr>
                            <th scope="row">@item.Date.ToLocalTime()</th>
                            <td>@item.UserName</td>
                            <td>@item.PoliclinicName</td>
                            <td>@item.HospitalName</td>
                            @if (item.IsActive == true)
                            {
                                <td><span class="badge bg-success">Aktif Randevu</span></td>
                                <td><a asp-action="Index" asp-controller="Prescription" asp-route-id="@item.Id" class="btn btn-info">Reçete</a></td>
                            }
                            else
                            {
                                <td><span class="badge bg-danger">İptal Edildi</span></td>
                                <td></td>
                            }

                        </tr>
                        }

                    </tbody>
                </table>
            }
            else
            {
                <p>Randevunuz bulunmamaktadır</p>
            }
        </div>
    </div>

</div>