hospitalAS.Web/Controllers/AppointmentController.cs
using hospitalAS.Business.Interfaces;
using hospitalAS.Dto.AppointmentDtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace hospitalAS.Web.Controllers
{
    [Authorize]
    public class AppointmentController : Controller
    {
        private readonly IAppointmentService _appointmentService;
        private readonly IUserService _userService;
        private readonly IHospitalService _hospitalService;
        private readonly IPoliclinicService _policlinicService;
        public AppointmentController(IAppointmentService appointmentService, IPoliclinicService policlinicService, IHospitalService hospitalService, IUserService userService)
        {
            _userService = userService;
            _hospitalService = hospitalService;
            _appointmentService = appointmentService;
            _policlinicService = policlinicService;
        }
        private async Task<int> GetUserId()
        {
            var identityNumber = User.Claims.FirstOrDefault(o => o.Type == ClaimTypes.NameIdentifier).Value;
            int userId = await _userService.GetUserIdByIdentityNumber(identityNumber);
            return userId;
        }
        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> Index()
        {
            ViewBag.Hospitals = new SelectList(await _hospitalService.GetAllHospitals(), "Id", "Name");
            var appointments = await _appointmentService.GetAllAppointmentsByUserId(await GetUserId());
            return View(appointments);
        }
        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> PoliclinicList(int id)
        {
            var jsonString = JsonConvert.SerializeObject(await _policlinicService.GetPoliclinicsByHospitalId(id));
            return Json(jsonString);
        }
        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> DoctorList(int id)
        {
            var jsonString = JsonConvert.SerializeObject(await _userService.GetDoctorsByPoliclinicId(id));
            return Json(jsonString);
        }
        [Authorize(Roles = "Patient")]
        [HttpPost]
        public async Task<IActionResult> TakeAnAppointment(AddAppointmentDto model)
        {
             model.PatientId = await GetUserId(); 
            await _appointmentService.AddAppointment(model);
            return Json("true");
        }
        [Authorize(Roles = "Doctor")]
        public async Task<IActionResult> PatientList()
        {
            var patients = await _appointmentService.GetAllAppointmentsByDoctorId(await GetUserId());
            return View(patients);
        }
        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> OutOfDateAppointment()
        {
            var appointments = await _appointmentService.GetOutOfDateAppointmentByUserId(await GetUserId());
            return View(appointments);
        }
        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> CancelAppointment(int id)
        {
            await _appointmentService.DeleteAppointment(id);
            return RedirectToAction("Index");
        }
    }
}

hospitalAS.Web/Controllers/AuthController.cs
using AutoMapper;
using hospitalAS.Business.Interfaces;
using hospitalAS.Dto.ClaimDtos;
using hospitalAS.Dto.UserDtos;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace hospitalAS.Web.Controllers
{
    public class AuthController : Controller
    {
       
        private readonly IBloodTypeService _bloodTypeService;
        private readonly IUserService _userService;
        private readonly IMapper _mapper;
        public AuthController(IUserService userService, IBloodTypeService bloodTypeService, IMapper mapper)
        {
            _userService = userService;
            _bloodTypeService = bloodTypeService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginDto model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userService.ValidateUser(model.IdentityNumber, model.Password);
                if (user != null)
                {
                    await CreateClaim(_mapper.Map<ClaimDto>(user));
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("Giriş yap", "Kullanıcı adı veya şifre hatalı");
            }
            return View("Index");
        }

        private async Task CreateClaim(ClaimDto model)
        {
            List<Claim> claims = new List<Claim>
                        {
                            new Claim(ClaimTypes.Name, model.Name),
                            new Claim(ClaimTypes.Surname, model.Surname),
                            new Claim(ClaimTypes.Role, model.Role.Name),
                            new Claim(ClaimTypes.NameIdentifier, model.IdentityNumber),
                        };
            ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(claimsPrincipal);
        }

        public async Task<IActionResult> Register()
        {
            ViewBag.BloodTypes = new SelectList(await _bloodTypeService.GetAllBloodTypes(), "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterDto model)
        {
            if (ModelState.IsValid)
            {
                int addedPatientId = await _userService.AddUser(model);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.BloodTypes = new SelectList(await _bloodTypeService.GetAllBloodTypes(), "Id", "Name");
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }

    }
}

hospitalAS.Web/Controllers/UserController.cs
using hospitalAS.Business.Interfaces;
using hospitalAS.Dto.UserDtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace hospitalAS.Web.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IBloodTypeService _bloodTypeService;
        private readonly IRoleService _roleService;
        public UserController(IBloodTypeService bloodTypeService, IUserService userService, IRoleService roleService)
        {
            _userService = userService;
            _bloodTypeService = bloodTypeService;
            _roleService = roleService;
        }
        public async Task<IActionResult> Index(int id)
        {
            ViewBag.BloodTypes = new SelectList(await _bloodTypeService.GetAllBloodTypes(), "Id", "Name");
            var patient = new UpdateUserDto();
            if (id > 0)
            {
                patient = await _userService.GetUser(id);
            }
            else
            {
                patient = await _userService.GetUser(await GetUserId());
            }
            return View(patient);
        }

        [HttpPost]
        public async Task<IActionResult> Index(UpdateUserDto model)
        {
            if (ModelState.IsValid)
            {                
                await _userService.UpdateUser(model);
                return RedirectToAction("Index");
            }
            ViewBag.BloodTypes = new SelectList(await _bloodTypeService.GetAllBloodTypes(), "Id", "Name");
            return View();

        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ListUser()
        {
            ViewBag.BloodTypes = new SelectList(await _bloodTypeService.GetAllBloodTypes(), "Id", "Name");
            ViewBag.Roles = new SelectList(await _roleService.GetAllRoles(), "Id", "Name");
            var users = await _userService.GetAllUser();
            return View(users);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AddUserViaAdmin(RegisterDto model)
        {
            ViewBag.BloodTypes = new SelectList(await _bloodTypeService.GetAllBloodTypes(), "Id", "Name");
            ViewBag.Roles = new SelectList(await _roleService.GetAllRoles(), "Id", "Name");
            var users = await _userService.AddUser(model);
            return Json("true");
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteUser(int id)
        {
            var user= await _userService.GetUser(id);
            user.IsActive = false;
            await _userService.UpdateUser(user);
            return RedirectToAction("ListUser");
        }

        private async Task<int> GetUserId()
        {
            var identityNumber = User.Claims.FirstOrDefault(o => o.Type == ClaimTypes.NameIdentifier).Value;
            int userId = await _userService.GetUserIdByIdentityNumber(identityNumber);
            return userId;
        }
    }
}

hospitalAS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - hospitalAS.Web</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!-- CSS here -->
    <link rel="stylesheet" href="~/theme/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/theme/css/magnific-popup.css">
    <link rel="stylesheet" href="~/theme/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/theme/css/themify-icons.css">
    <link rel="stylesheet" href="~/theme/css/nice-select.css">
    <link rel="stylesheet" href="~/theme/css/flaticon.css">
    <link rel="stylesheet" href="~/theme/css/gijgo.css">
    <link rel="stylesheet" href="~/theme/css/animate.css">
    <link rel="stylesheet" href="~/theme/css/slicknav.css">
    <link rel="stylesheet" href="~/theme/css/style.css">
    <link href="~/lib/alertify/css/alertify.min.css" rel="stylesheet" />
    <style>
        a {
            text-decoration: none;
        }
    </style>

    @await RenderSectionAsync("Styles", required: false)
</head>
<body>

    <!-- header-start -->
    <header>
        <div class="header-area ">

            <div id="sticky-header" class="main-header-area bg-info">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-2">
                            <div class="logo">
                                <a href="index.html">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-7">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a class=" text-white" asp-action="Index" asp-controller="Home">Anasayfa</a></li>
                                        @if (User.IsInRole("Doctor")  && User.Identity.IsAuthenticated)
                                        {
                                            <li><a class=" text-white" asp-action="PatientList" asp-controller="Appointment">Hastalar</a></li>
                                        }
                                        @if (User.IsInRole("Patient") && User.Identity.IsAuthenticated)
                                        {
                                            <li>
                                                <a class=" text-white" href="#">Randevu <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">

                                                    <li><a asp-action="Index" asp-controller="Appointment">Aktif Randevular</a></li>
                                                    <li><a asp-action="OutOfDateAppointment" asp-controller="Appointment">Geçmiş Randevular</a></li>
                                                </ul>
                                            </li>
                                        }
                                        <li>
                                            <a class=" text-white" href="#">Merhaba @User.Identity.Name <i class="ti-angle-down"></i></a>
                                            <ul class="submenu">
                                                <li><a asp-action="Index" asp-controller="User">Profil</a></li>
                                                @if (User.IsInRole("Admin") && User.Identity.IsAuthenticated)
                                                {
                                                    <li><a asp-action="ListUser" asp-controller="User">Kullanıcılar</a></li>
                                                }
                                                <li><a asp-action="Logout" asp-controller="Auth">Çıkış Yap</a></li>
                                            </ul>
                                        </li>

                                    </ul>
                                </nav>
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - hospitalAS.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/alertify/alertify.min.js"></script>
    <!-- JS here -->
    <script src="~/theme/js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="~/theme/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/theme/js/popper.min.js"></script>
    <script src="~/theme/js/owl.carousel.min.js"></script>
    <script src="~/theme/js/isotope.pkgd.min.js"></script>
    <script src="~/theme/js/ajax-form.js"></script>
    <script src="~/theme/js/waypoints.min.js"></script>
    <script src="~/theme/js/jquery.counterup.min.js"></script>
    <script src="~/theme/js/imagesloaded.pkgd.min.js"></script>
    <script src="~/theme/js/scrollIt.js"></script>
    <script src="~/theme/js/jquery.scrollUp.min.js"></script>
    <script src="~/theme/js/wow.min.js"></script>
    <script src="~/theme/js/nice-select.min.js"></script>
    <script src="~/theme/js/jquery.slicknav.min.js"></script>
    <script src="~/theme/js/jquery.magnific-popup.min.js"></script>
    <script src="~/theme/js/plugins.js"></script>
    <script src="~/theme/js/gijgo.min.js"></script>
    <!--contact js-->
    <script src="~/theme/js/contact.js"></script>
    <script src="~/theme/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/theme/js/jquery.form.js"></script>
    <script src="~/theme/js/jquery.validate.min.js"></script>
    <script src="~/theme/js/mail-script.js"></script>

    <script src="~/theme/js/main.js"></script>
    <script>
        $('#datepicker').datepicker({
            iconsLibrary: 'fontawesome',
            icons: {
                rightIcon: '<span class="fa fa-caret-down"></span>'
            }
        });
        $('#datepicker2').datepicker({
            iconsLibrary: 'fontawesome',
            icons: {
                rightIcon: '<span class="fa fa-caret-down"></span>'
            }

        });
        $(document).ready(function () {
            $('.js-example-basic-multiple').select2();
        });
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

hospitalAS.Web/Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="~/theme/img/favicon.png">
    <!-- Place favicon.ico in the root directory -->
    <!-- CSS here -->
    <link rel="stylesheet" href="~/theme/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/theme/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/theme/css/magnific-popup.css">
    <link rel="stylesheet" href="~/theme/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/theme/css/themify-icons.css">
    <link rel="stylesheet" href="~/theme/css/nice-select.css">
    <link rel="stylesheet" href="~/theme/css/flaticon.css">
    <link rel="stylesheet" href="~/theme/css/gijgo.css">
    <link rel="stylesheet" href="~/theme/css/animate.css">
    <link rel="stylesheet" href="~/theme/css/slicknav.css">
    <link rel="stylesheet" href="~/theme/css/style.css">
    <!-- <link rel="stylesheet" href="~/theme/css/responsive.css"> -->
    <link href="~/lib/alertify/css/alertify.min.css" rel="stylesheet" />

</head>
<body>
    <div>
        @RenderBody()
    </div>
    <!-- JS here -->
    <script src="~/theme/js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="~/theme/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/theme/js/popper.min.js"></script>
    <script src="~/theme/js/bootstrap.min.js"></script>
    <script src="~/theme/js/owl.carousel.min.js"></script>
    <script src="~/theme/js/isotope.pkgd.min.js"></script>
    <script src="~/theme/js/ajax-form.js"></script>
    <script src="~/theme/js/waypoints.min.js"></script>
    <script src="~/theme/js/jquery.counterup.min.js"></script>
    <script src="~/theme/js/imagesloaded.pkgd.min.js"></script>
    <script src="~/theme/js/scrollIt.js"></script>
    <script src="~/theme/js/jquery.scrollUp.min.js"></script>
    <script src="~/theme/js/wow.min.js"></script>
    <script src="~/theme/js/nice-select.min.js"></script>
    <script src="~/theme/js/jquery.slicknav.min.js"></script>
    <script src="~/theme/js/jquery.magnific-popup.min.js"></script>
    <script src="~/theme/js/plugins.js"></script>
    <script src="~/theme/js/gijgo.min.js"></script>
    <!--contact js-->
    <script src="~/theme/js/contact.js"></script>
    <script src="~/theme/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/theme/js/jquery.form.js"></script>
    <script src="~/theme/js/jquery.validate.min.js"></script>
    <script src="~/theme/js/mail-script.js"></script>

    <script src="~/theme/js/main.js"></script>

    <script>
        $('#datepicker').datepicker({
            iconsLibrary: 'fontawesome',
            icons: {
                rightIcon: '<span class="fa fa-caret-down"></span>'
            }
        });
        $('#datepicker2').datepicker({
            iconsLibrary: 'fontawesome',
            icons: {
                rightIcon: '<span class="fa fa-caret-down"></span>'
            }

        });
        $(document).ready(function () {
            $('.js-example-basic-multiple').select2();
        });
    </script>
    <script src="~/lib/alertify/alertify.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>